CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    userpassword VARCHAR(255) NOT NULL,
    zipcode VARCHAR(255) DEFAULT NULL,
    UNIQUE (username)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS carbonfootprints (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    footprint VARCHAR(255) NOT NULL
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS challenges (
    id INT AUTO_INCREMENT PRIMARY KEY,
    challenge VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL
) ENGINE=INNODB;

