version: '3.7'

services:
        db:
                container_name: co2mysqldemo
                image: mysql
                ports:
                        - 3306:3306
                environment:
                        MYSQL_ROOT_PASSWORD: secret
                        MYSQL_DATABASE: demo

        backend:
                build:
                        context: .
                        dockerfile: ./Dockerfile
                ports:
                        - 8080:8080
                environment:
                        - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/demo?allowPublicKeyRetrieval=true&useSSL=false
